[[Member]]
== Member API

=== 로그인된 상태로 나의 회원 정보 조회

operation::members-get-own[snippets='error-code-table,http-request,http-response']

=== 회원 정보 조회

==== 부가 조건
- 로그인 시 회원 정보를 조회하려면 헤더에 토큰 정보가 필요
`Authorization: Bearer Token`

operation::members-get-by-memberId[snippets='error-code-table,http-request,http-response']

=== 로그인된 상태로 나의 회원 정보 수정

operation::members-update[snippets='error-code-table,http-request,http-response']

=== 회원 검색

==== 검색 조건

- GitHub ID를 query로 하여 검색
- 없을 경우 모든 회원 조회

==== careerLevel 조건

- `none` (경력 없음)
- `junior` (0~2년차)
- `midlevel` (3~5년차)
- `senior` (6년차 이상)
- 없을 경우 모든 회원 조회

==== jobType 조건

- `backend` (백엔드)
- `frontend` (프론트엔드)
- `mobile` (모바일)
- `etc` (기타)

==== sort 조건

- `followerCount,desc`(팔로워 수 순)
- 없을 경우 등록 순서

==== 부가 조건
- 로그인 시 회원 정보를 조회하려면 헤더에 토큰 정보가 필요
`Authorization: Bearer Token`

operation::members-search[snippets='error-code-table,http-request,http-response']

=== 다른 회원 팔로우

operation::follow[snippets='error-code-table,http-request,http-response']

=== 다른 회원 언팔로우

operation::unfollow[snippets='error-code-table,http-request,http-response']

=== 팔로우하는 회원 검색

==== 검색 조건

- GitHub ID를 query로 하여 검색
- 없을 경우 모든 회원 조회

==== careerLevel 조건

- `none` (경력 없음)
- `junior` (0~2년차)
- `midlevel` (3~5년차)
- `senior` (6년차 이상)
- 없을 경우 모든 회원 조회

==== jobType 조건

- `backend` (백엔드)
- `frontend` (프론트엔드)
- `mobile` (모바일)
- `etc` (기타)

==== sort 조건

- `followerCount,desc`(팔로워 수 순)
- 없을 경우 등록 순서

operation::search-followings[snippets='error-code-table,http-request,http-response']
