[[Product]]
== Product API

=== 제품 단일 제품 조회

operation::products-get[snippets='error-code-table,http-request,http-response']

=== 제품 목록 페이지 조회

==== 검색 조건

- 제품 이름을 query로 하여 검색
- 없을 경우 모든 제품 조회

==== category 조건

- `keyboard` (키보드)
- `mouse` (마우스)
- `monitor` (모니터)
- `stand` (거치대)
- `software` (소프트웨어)
- 없을 경우 모든 제품 조회

==== sort 조건

- `rating,desc`(평점순)
- `reviewCount,desc`(리뷰 많은순)
- 없을 경우 등록 순서

operation::products-page-get[snippets='error-code-table,http-request,http-response']

=== 특정 제품의 사용자 통계를 조회

operation::products-member-statistics-get[snippets='error-code-table,http-request,http-response']

=== 인기 상품 조회

operation::products-popular-list-get[snippets='error-code-table,http-request,http-response']

=== 제품 추가(어드민)

operation::admin-products-create[snippets='error-code-table,http-request,http-response']

=== 제품 수정(어드민)

operation::admin-products-update[snippets='error-code-table,http-request,http-response']

=== 제품 삭제(어드민)

operation::admin-products-delete[snippets='error-code-table,http-request,http-response']
