[[Reivew]]
== Review API

=== 리뷰 작성

operation::reviews-create[snippets='error-code-table,http-request,http-response']

=== 특정 제품의 리뷰 목록 페이지 조회

==== sort 조건

- 조건을 적지 않는 경우 (최신순)
- `rating,desc`(평점순)

operation::reviews-by-product-page-get[snippets='error-code-table,http-request,http-response']

=== 모든 리뷰 목록 페이지 조회

==== sort 조건

- 조건을 적지 않는 경우 (최신순)
- `rating,desc`(평점순)

operation::reviews-page-get[snippets='error-code-table,http-request,http-response']

=== 내가 작성한 리뷰 목록 페이지 조회

==== sort 조건

- 조건을 적지 않는 경우 (최신순)
- `rating,desc`(평점순)

operation::reviews-page-get-own[snippets='error-code-table,http-request,http-response']

=== 회원의 아이디로 리뷰 목록 페이지 조회

==== sort 조건

- 조건을 적지 않는 경우 (최신순)
- `rating,desc`(평점순)

operation::reviews-page-get-by-memberId[snippets='error-code-table,http-request,http-response']

=== 인벤토리 아이디로 리뷰 조회

operation::reviews-get-by-inventoryProductId[snippets='error-code-table,http-request,http-response']

=== 리뷰 수정

operation::reviews-update[snippets='error-code-table,http-request,http-response']

=== 리뷰 삭제

operation::reviews-delete[snippets='error-code-table,http-request,http-response']
